# Generated by Django 3.1.5 on 2022-04-26 14:31

import datetime

from django.db import migrations, models


def update_base_date_distributors(apps, schema_editor):
    DataDistributor = apps.get_model("insights", "DataDistributor")
    google = {"name": "Google", "base_date": "2014-10-28"}
    apple = {"name": "Apple", "base_date": "2014-09-17"}
    # Clarity Core Distributor (non saved instances) will use date.today (deploy date)
    DataDistributor.objects.filter(name__icontains=google["name"]).update(
        base_date=google["base_date"]
    )
    DataDistributor.objects.filter(name__icontains=apple["name"]).update(
        base_date=apple["base_date"]
    )


def delete_ledgers_older_than_distributor_release(apps, schema_editor):
    DataDistributorLedger = apps.get_model("insights", "DataDistributorLedger")
    DataDistributor = apps.get_model("insights", "DataDistributor")
    for d in DataDistributor.objects.all():
        DataDistributorLedger.objects.filter(
            distributor=d, started_at__lt=d.base_date
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_squashed_0017_patienthealthinsight_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="datadistributor",
            name="base_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RunPython(update_base_date_distributors),
        migrations.RunPython(delete_ledgers_older_than_distributor_release),
    ]
