# Generated by Django 3.1.5 on 2022-05-06 21:02

from django.db import migrations, models


def update_in_devices_aggregation(apps, schema_editor):
    HealthInsight = apps.get_model("insights", "HealthInsight")
    for h in HealthInsight.objects.filter(statistic__name__iexact="MIN"):
        h.in_devices_aggregation = 'min'
        h.save()


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0018_datadistributor_base_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsight',
            name='in_devices_aggregation',
            field=models.CharField(choices=[('avg', 'avg'), ('max', 'max'), ('min', 'min'), ('sum', 'sum')], default='max', max_length=3),
            preserve_default=False,
        ),
        migrations.RunPython(update_in_devices_aggregation),
    ]
