# Generated by Django 3.1.5 on 2022-12-15 23:44

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    # replaces = [ # Keeping this here for reference, but it's not needed anymore
    #     ("insights", "0020_auto_20220802_0401"),
    #     ("insights", "0021_healthinsightcategory"),
    #     ("insights", "0022_patientrecommendation_recommendation"),
    #     ("insights", "0021_healthinsight_chart_type"),
    #     ("insights", "0023_merge_20221004_1347"),
    #     ("insights", "0024_healthinsightstatevalue"),
    # ]

    dependencies = [
        ("patients", "0010_auto_20211021_0313"),
        ("insights", "0019_healthinsight_in_devices_aggregation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datadevice",
            name="version",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name="HealthInsightCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
                (
                    "health_insights",
                    models.ManyToManyField(
                        related_name="categories", to="insights.HealthInsight"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthInsightRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "health_insights",
                    models.ManyToManyField(
                        related_name="in_recommendations", to="insights.HealthInsight"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientHealthInsightRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_insights_recommendations",
                        to="patients.patient",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients_recommendations",
                        to="insights.healthinsightrecommendation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="healthinsight",
            name="chart_type",
            field=models.CharField(
                choices=[("line", "Line"), ("bar", "Bar")],
                default="line",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="HealthInsightStateValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reversed_cumulative", models.BooleanField(default=False)),
                (
                    "applies_to_gender",
                    models.CharField(
                        choices=[
                            ("All", "All"),
                            ("Female", "Female"),
                            ("Male", "Male"),
                        ],
                        default="All",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Unknown", "Unknown"),
                            ("Risk", "Risk"),
                            ("Warning", "Warning"),
                            ("Success", "Success"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "upper_limit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "lower_limit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "health_insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="insights.healthinsight",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("health_insight", "state", "applies_to_gender"),
                    ("health_insight", "upper_limit", "lower_limit"),
                },
            },
        ),
    ]
