# Generated by Django 3.1.5 on 2022-11-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0025_seed_health_insight_state_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthealthinsight',
            name='data_distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients_health_insights', to='insights.datadistributor'),
        ),
    ]
