# Generated by Django 3.1.5 on 2022-11-16 13:17
import logging
from datetime import timedelta

from django.db import migrations

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    def populate_goals_recommendations(self, schema_editor):
        Goal = self.get_model("insights", "Goal")
        goals = [
            {
                "name": "Weight loss [Steps]",
                "aggregation_type": "avg",
                "aggregation_period": timedelta(days=30),
                "value": 10000,
                "value_unit": "steps",
            },
            {
                "name": "Weight loss [Calories]",
                "aggregation_type": "avg",
                "aggregation_period": timedelta(days=30),
                "value": 500,
                "value_unit": "kcal",
            },
            {
                "name": "Sleep optimization",
                "aggregation_type": "avg",
                "aggregation_period": timedelta(days=30),
                "value": 7,
                "value_unit": "hours",
            },
            {
                "name": "Performance Men",
                "aggregation_type": "avg",
                "aggregation_period": timedelta(days=30),
                "value": 60,
                "value_unit": "bpm",
            },
            {
                "name": "Performance Women",
                "aggregation_type": "avg",
                "aggregation_period": timedelta(days=30),
                "value": 80,
                "value_unit": "bpm",
            },
        ]
        logger.info("Creating goals")
        Goal.objects.bulk_create([Goal(**data) for data in goals])

    dependencies = [
        ("insights", "0028_goals_recommendations_triggers__20221128_2110"),
    ]

    operations = [
        migrations.RunPython(populate_goals_recommendations, migrations.RunPython.noop),
    ]
