# Generated by Django 3.1.5 on 2022-12-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0029_populate_goals_recommendations_20221116_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthinsight',
            name='last_collection_time',
            field=models.TimeField(null=True),
        ),
    ]
