# Generated by Django 3.1.5 on 2022-12-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    def delete_rules_not_equal(self, schema_editor):
        HealthInsightDisplayRule = self.get_model("insights", "HealthInsightDisplayRule")
        HealthInsightDisplayRule.objects.filter(comparator="!=").update(
            comparator=">=", comparison_value="0"
        )
        HealthInsightDisplayRule.objects.filter(field="collection_date").update(
            comparator=">="
        )

    dependencies = [
        ('insights', '0030_patienthealthinsight_last_collection_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsightdisplayruleset',
            name='show_null',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthinsightdisplayrule',
            name='comparator',
            field=models.CharField(choices=[('==', 'Equal'), ('<', 'Less Than'), ('<=', 'Less Than Equal'), ('>', 'Greater Than'), ('>=', 'Greater Than Equal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='healthinsightdisplayrule',
            name='comparison_value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthinsightdisplayrule',
            name='comparison_value_type',
            field=models.CharField(choices=[('decimal', 'Decimal'), ('days', 'Days Ago')], default='decimal', max_length=25),
        ),
        migrations.RunPython(delete_rules_not_equal, migrations.RunPython.noop),
    ]
