# Generated by Django 3.1.5 on 2022-12-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0031_displayrules_updates_20221209_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsightdisplayrule',
            name='comparison_value',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='healthinsightdisplayrule',
            name='comparison_value_type',
            field=models.CharField(choices=[('decimal', 'Decimal'), ('days', 'Days Ago')], default='decimal', max_length=8),
        ),
        migrations.AlterField(
            model_name='healthinsightdisplayrule',
            name='field',
            field=models.CharField(choices=[('value', 'Value'), ('collection_date', 'Collection Date')], max_length=16),
        ),
        migrations.AlterField(
            model_name='healthinsightdisplayruleset',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
