# Generated by Django 3.1.5 on 2022-12-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0032_healthinsightdisplayrule_max_lengths_20221212_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorMarkerPair',
            fields=[
                ('distributormarker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insights.distributormarker')),
                ('value_function', models.CharField(choices=[('add', 'add'), ('subtract', 'subtract'), ('multiply', 'multiply'), ('divide', 'divide')], max_length=12)),
                ('units', models.CharField(blank=True, max_length=25)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_1', to='insights.distributormarker')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_2', to='insights.distributormarker')),
            ],
            options={
                'unique_together': {('first', 'second')},
            },
            bases=('insights.distributormarker',),
        ),
    ]
