# Generated by Django 3.1.5 on 2023-01-10 21:03

from django.db import migrations, models


def create_recommendation_triggers(apps, schema_editor):
    """Create RecommendationTriggers for all HealthInsightRecommendations"""

    HealthInsightRecommendation = apps.get_model(
        "insights", "HealthInsightRecommendation"
    )
    RecommendationTrigger = apps.get_model("insights", "RecommendationTrigger")
    try:
        calories = HealthInsightRecommendation.objects.get(
            goal__value=500, goal__value_unit="kcal"
        )
        steps = HealthInsightRecommendation.objects.get(
            goal__value=10000, goal__value_unit="steps"
        )
        sleep = HealthInsightRecommendation.objects.get(
            goal__value=7, goal__value_unit="hours"
        )
        resting_hr_men = HealthInsightRecommendation.objects.get(
            goal__value=60, goal__value_unit="bpm"
        )
        resting_hr_women = HealthInsightRecommendation.objects.get(
            goal__value=80, goal__value_unit="bpm"
        )
        weight = HealthInsightRecommendation.objects.get(
            goal__value=500, goal__value_unit="kcal"
        )
    except HealthInsightRecommendation.DoesNotExist:
        return

    RecommendationTrigger.objects.update_or_create(
        proxy_trigger="TriggerCalories", recommendation=calories
    )
    RecommendationTrigger.objects.update_or_create(
        proxy_trigger="TriggerSteps", recommendation=steps
    )
    RecommendationTrigger.objects.update_or_create(
        proxy_trigger="TriggerSleep", recommendation=sleep
    )
    RecommendationTrigger.objects.update_or_create(
        proxy_trigger="TriggerRestingHR", recommendation=resting_hr_men
    )
    RecommendationTrigger.objects.update_or_create(
        proxy_trigger="TriggerRestingHR", recommendation=resting_hr_women
    )
    RecommendationTrigger.objects.update_or_create(
        proxy_trigger="TriggerWeight", recommendation=weight
    )


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0034_update_calories_insights"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationtrigger",
            name="proxy_trigger",
            field=models.CharField(
                choices=[
                    ("TriggerCalories", "Calories"),
                    ("TriggerRestingHR", "Resting Heart Rate"),
                    ("TriggerSleep", "Sleep"),
                    ("TriggerSteps", "Steps"),
                    ("TriggerWeight", "Weight"),
                ],
                default=None,
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(create_recommendation_triggers, migrations.RunPython.noop),
    ]
